version: 0.2         

phases:
  install:
    commands:
      - echo Installing... Running npm install
      - npm install
  pre_build:
    commands:
      - echo Pre-build...
  build:
    commands:
      - echo Building... Running npm test
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: wealthx-$(date +%Y-%m-%d) 
